registration:
   users:
      -
        name: Козлов Антон Викторович
        phone: "+79099520361"
        email: iogann1978@gmail.com
      -
        name: Богданова Анна Валентиновна
        phone: "+79057614573"
        email: alma10@list.ru

html:
   urireg: https://dni-naslediya.ru/calendar/reserve.php
   sites:
      - https://www.dni-naslediya.ru/calendar/object/vysoko-petrovskiy-monastyr/
      - https://www.dni-naslediya.ru/calendar/object/novodeviche-kladbishche/

spring:
   mail:
      host: smtp.gmail.com
      port: 465
      username: kornej.yashma@gmail.com
      password: Sicherheit1978
      properties.mail.smtp:
         auth: true
         starttls:
            enable: true
            required: true
         ssl.enable: true
      test-connection: true