html:
   sites:
      - https://dni-naslediya.ru/calendar/object/kryshi-bashni-i-truby-fabriki-eynem/

spring:
   mail:
      host: smtp.gmail.com
      port: 465
      username: kornej.yashma@gmail.com
      password: Sicherheit1978
      properties.mail.smtp:
         auth: true
         starttls:
            enable: true
            required: true
         ssl.enable: true
      test-connection: true