registration:
   users:
      -
        FIO: Козлов Антон Викторович
        PHONE: "+79099520361"
        EMAIL: iogann1978@gmail.com
      -
        FIO: Богданова Анна Валентиновна
        PHONE: "+79057614573"
        EMAIL: alma10@list.ru

html:
   domain: https://dni-naslediya.ru
   urilist: https://dni-naslediya.ru/calendar/free/
   urireg: https://dni-naslediya.ru/calendar/cr2019.php

spring:
   mail:
      host: smtp.gmail.com
      port: 465
      username: kornej.yashma@gmail.com
      password: Sicherheit1978
      properties.mail.smtp:
         auth: true
         starttls:
            enable: true
            required: true
         ssl.enable: true
      test-connection: true